name: checks

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

env:
  MNEMONIC: "exchange vintage ocean narrow danger return culture ignore trim solve clock hidden buddy wise emotion"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: pnpm run lint

  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: pnpm typechain
      - run: pnpm test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run coverage
        run: pnpm run coverage
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
